### DISCUSSION TITLE
How can I make ESLint use cache when running on GitHub actions?

### DISCUSSION THREAD

**Discussion by agos** [eslint/eslint#16997] [Q&A] [answered]
Since my project is getting bigger, I've started using ESLint's `--cache` option. 

When running locally as a pre-commit hook, I get a nice speedup, from ~30s to ~1s.

When running on GitHub Actions, though, all the files will result changed and the cache will not be used at all.

### Github Actions Workflow Setup:

```yaml
- name: ESLint cache
  uses: actions/cache@v3
  with:
    path: .eslintcache

    key: |
      ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.js') }}
    restore-keys: |
      ${{ runner.os }}-eslint-

- name: Run ESLint
  run: ./node_modules/eslint/bin/eslint.js ./src --ext .ts,.tsx --cache --cache-strategy content --debug
```

### Debug output

ESLint says it has picked up the configuration:

```log
eslint:lint-result-cache Caching results to /home/runner/work/[...].eslintcache
eslint:lint-result-cache Using "content" strategy to detect changes
```

but for every file, the log will show:

```log
eslintrc:cascading-config-array-factory Cache hit: /home/runner/work/[...]/dir.
eslint:lint-result-cache Cache entry not found or no longer valid: /home/runner/work/[...]/dir/file.ext
```

I thought that `--cache-strategy content` would avoid exactly this, so I'm a bit stumped. Does anybody have an idea on how to configure GitHub actions and ESLint's cache to play well with each other?

Thanks in advance
