### DISCUSSION TITLE
making a new repo for github action config files

### DISCUSSION THREAD

**Discussion by aladdin-add** [eslint/eslint#17424] [Ideas]
Currently eslint repos are using their own github action configurations, which is the easiest and most popular way. However, the disadvantage is that when we need to make changes, we have to do it in each repository, which is not very convenient. So I suggest we create a new repository (e.g. gh-actions or gha) to store the shared configuration. At least the following configuration files are to be considered:

* release-please
* add-to-triage
* renovate
* stale
* codeql

Refs: https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization

**Comment by mdjermanovic** [comment]
That would be great, but is there a working example with public repositories? The documentation you linked sounds like this is possible only with private repositories.

**Reply by aladdin-add** [reply]
renovate does support shared configs, and I tried it in my fork: https://github.com/aladdin-add/eslint/blob/93802d143d26e260e41b05be6ce44572b77ad9f5/.github/renovate.json#L2

I'm not sure if it's possible for all others, will investigate later.

**Reply by voxpelli** [reply]
It is possible, see:

* [fastify/workflows](https://github.com/fastify/workflows)
* [mdn/workflows](https://github.com/mdn/workflows)
* [SocketDev/workflows](https://github.com/SocketDev/workflows)
* [my workflows](https://github.com/voxpelli/ghatemplates)

And using them is really simple:

```yml
name: Node CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: voxpelli/ghatemplates/.github/workflows/test.yml@main
    with:
      node-versions: '16,18,20'
      os: 'ubuntu-latest,windows-latest'
```
