### ISSUE TITLE
Losing recursivity

### ISSUE THREAD

**Issue by micky2be** [eslint/eslint#10464]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
parser: babel-eslint
extends: airbnb

env:
  browser: true
  es6: true

rules:
  comma-dangle: [2, never]
  max-len:
    - error
    - 100
    - 2
    - { ignoreUrls: true, ignoreComments: false }
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
$ yarn eslint src/**/*.jsx
```

**What did you expect to happen?**
Parsing all my files with the extension `jsx` under the folder `src`

**What actually happened? Please include the actual, raw output from ESLint.**
It parsed the first file it found and stopped
