### ISSUE TITLE
Rule lines-around-comment not triggering at begin of file

### ISSUE THREAD

**Issue by ReiKratos** [eslint/eslint#10831]
* **ESLint Version:** 4.12.1
* **Node Version:** 9.11.1
* **npm Version:** 6.4.1

**Parser:** Babel-eslint

**Configuration:**
```yml
rules:
  lines-around-comment: ["error", {
    afterBlockComment: true,
    beforeBlockComment: true,
    }
  ]
```

With that configuration, the following code is supposed to throw an error:

```js
/*
 * Some comment.
 */
```

However, when block comment starts at the first line of the file, the rule doesn't trigger. Is it on purpose? If it is, why is that?
