### ISSUE TITLE
padding-line-between-statements doesn't treat IIFEs as functions

### ISSUE THREAD

**Issue by LJNeon** [eslint/eslint#10843]
**Tell us about your environment**

* **ESLint Version:** 5.5.0
* **Node Version:** 10.9.0
* **npm Version:** 6.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
env: {
  es6: true,
  node: true
}

extends: "eslint:recommended"

rules: {
  padding-line-between-statements: [2, {
    blankLine: "never",
    next: "*",
    prev: "*"
  },
  {
    blankLine: "always",
    next: "function",
    prev: "*"
  },
  {
    blankLine: "always",
    next: "*",
    prev: "function"
  }]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
process.on("unhandledRejection", (r, p) => {
  // ...
});
// <---- eslint wants me to remove this blank line
(async () => {
  // ...
})();
```

```bash
eslint . --ext .js
```

**What did you expect to happen?**
It would consider the code valid as I've stated that function should have blank lines both before and after.
**What actually happened? Please include the actual, raw output from ESLint.**
```bash
/../src/index.js
  34:1  error  Unexpected blank line before this statement  padding-line-between-statements
```
