### ISSUE TITLE
`overrides` settings in shareable configs overwrite extender's setting

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#11510]
This issue came from https://github.com/eslint/rfcs/pull/13.

> Currently, `overrides` is applied after all `overrides` properties are merged. This means that the `overrides` in a shareable config priors to the setting in your `.eslintrc` file.
> 
> ```yml
> extends:
>     - foo
> rules:
>     eqeqeq: error # silently ignored if the "foo" has the "eqeqeq" setting in "overrides".
> ```
> 
> After this proposal, the setting in your `.eslintrc` file priors to the setting in shareable configs always. This is a breaking change, but I think this is a bug fix.
>
> https://github.com/eslint/rfcs/blob/42cd563d23eaaad5e9206d8ca7463aeb7dc75a69/designs/2019-eslintrc-improvements/README.md#%EF%B8%8F-fix-a-surprised-behavior-of-overrides

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```yml
# extendee.yml
overrides:
  - files: "*.js"
    rules:
      no-console: error
```

```yml
# extender.yml
extends: "./extendee.yml"
rules:
  no-console: off
```

```
echo "console.log()" | eslint --stdin --stdin-filename a.js --no-eslintrc --config extender.yml
```

**What did you expect to happen?**

No errors because `extender.yml` disabled `no-console` rule.

**What actually happened? Please include the actual, raw output from ESLint.**

```
C:\Users\t-nagashima.AD\dev\eslint\a.js
  1:1  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)
```
