### ISSUE TITLE
No support for `jasmine` environment

### ISSUE THREAD

**Issue by whitneyit** [eslint/eslint#1176]
When using [eslint](https://github.com/eslint/eslint) to lint my [jasmine](http://jasmine.github.io/) test files, I have to constantly define a following list of globals in my `.eslintrc`, or worse still my test files.

``` yaml
# .eslintrc yaml

---
  globals:
    afterEach: false
    beforeEach: false
    describe: false
    expect: false
    it: false
    jasmine: false
    pending: false
    spyOn: false
    waits: false
    waitsFor: false
    xdescribe: false
    xit: false

    beforeAll: false
    afterAll: false
    runs: false
```

This list of globals covers both version [1.3](http://jasmine.github.io/1.3/introduction.html) and [2.0](http://jasmine.github.io/2.0/introduction.html).
