### ISSUE TITLE
max-len: comments: ignores JSX

### ISSUE THREAD

**Issue by avalanche1** [eslint/eslint#12213]
**Tell us about your environment**

* **ESLint Version:**
^6.1.0
* **Node Version:**
12.9.0
* **npm Version:**
6.9.0
**What parser (default, Babel-ESLint, etc.) are you using?**
"@typescript-eslint/parser": ^2.0.0
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
env:
  #https://medium.com/@jzarzoso/setting-eslint-on-meteor-for-react-development-10af658b44e2
  browser: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "hardcore-fp"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
#  project: "./tsconfig.json"
  ecmaVersion: "2019"
  sourceType: module
plugins:
  - "@typescript-eslint/eslint-plugin"
  - jest
  - react
  - react-hooks
  - promise
overrides:
  - files:
      - "*.test.js"
      - "*.spec.js"
    rules:
      fp/no-unused-expression: "off"
rules:
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/interface-name-prefix":
    - error
    - prefixWithI: always
  "@typescript-eslint/no-use-before-define": off
  arrow-body-style: "off"
  camelcase: off
  comma-dangle: "off"
  fp/no-mutating-methods:
    - error
    # Allow reassign Lodash methods
    - allowedObjects:
        - _
  fp/no-mutation:
    - error
    # Allow module.exports
    - commonjs: true
      allowThis: false
      # Allow assigning to window global
      exceptions:
        - object: window
#  fp/no-nil: "off"
  fp/no-unused-expression: "off"
  func-style: warn
  id-length:
    - warn
    - exceptions:
        - e
        - f
        - i
        - v
        - x
        - "y"
        - z
  id-match:
    - error
    - "^[a-zA-Z_]*$"
    - properties: true
  indent: off
  lines-around-comment:
    - warn
    - ignorePattern: /prettier-ignore/
  max-len:
    - warn
    - code: 90
      comments: 120
      tabWidth: 2
      ignorePattern: "import"
      ignoreUrls: true
  max-params:
    - error
    - 6
  multiline-ternary: "off"
  new-cap: off
  no-inline-comments: "off"
  no-magic-numbers:
    - error
    - ignore:
        - 0
        - 1
  no-multi-spaces: "off"
  no-return-await: off
  no-param-reassign:
    - error
    - props: true
  no-nested-ternary: "off"
  no-shadow:
    - error
    - builtinGlobals: true
  no-warning-comments: warn
  no-undef: error
  no-unneeded-ternary: "off"
  no-unused-vars: warn
  no-use-before-define: "off"
  object-curly-newline: "off"
  one-var: off
  operator-linebreak:
    - error
    - before
    - overrides:
        =: ignore
  padding-line-between-statements: "off"
  radix: "off"
  react/no-string-refs:
    - error
    - noTemplateLiterals: true
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/display-name: "off"
  react/prop-types: "off"
  semi: warn
settings: {}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export function ScoringResultsItem() {
  return (
    <List.Item>
      <Checkbox checked={state.checked}>
        <Avatar src={bankDatum.logoURL} />
        {/* Some really really really really really really really really really long comment */}
        <a href={bankDatum.PAURL} target="_blank">
          {bankDatum.name}
        </a>
      </Checkbox>
    </List.Item>
  );
}

```

```bash
eslint foo.js
```

**What did you expect to happen?**
no warnings logged

**What actually happened? Please include the actual, raw output from ESLint.**
`6:1   warning  This line has a length of 96. Maximum allowed is 90                                                                           max-len`

**Are you willing to submit a pull request to fix this bug?**
nope
