### ISSUE TITLE
Error while running ESLint: Invalid regular expression flags

### ISSUE THREAD

**Issue by eakl** [eslint/eslint#12538]
**Tell us about your environment**

* **ESLint Version:** 6.6.0
* **Node Version:** 12.13.0
* **npm Version:** 6.12.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
env:
  browser: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Creating any `*.js` file trigger the error. My linter in Atom report the following

**What did you expect to happen?**
No linter error flag when a JS file is created

**What actually happened? Please include the actual, raw output from ESLint.**
```
Error while running ESLint: Invalid regular expression flags
Invalid regular expression flags
Referenced from: /Users/me/dev/.eslintrc.yml

/Users/me/dev/node_modules/eslint/lib/source-code/source-code.js:426
return /\s/u.test(text.replace(/\/\*.*?\*\//gus, ""));
                               ^
```
