### ISSUE TITLE
TypeScript: `eslint --fix` command crash the code due to the `prefer-object-spread` rule

### ISSUE THREAD

**Issue by kurone-kito** [eslint/eslint#13058]
**Tell us about your environment**

- **ESLint Version:** v6.8.0
- **Node Version:** v13.11.0
- **npm Version:** v6.14.2

**What parser (default, Babel-ESLint, etc.) are you using?**

`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - prettier
root: true
rules:
  '@typescript-eslint/explicit-function-return-type':
    - 'off' # Because type inference cannot be used :(
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```ts
const getObject = () => ({ huge: ['sized'], dynamic: ['object'] });

const obj = Object.assign<{}, Record<string, string[]>>({}, getObject());
console.log(obj);
```

```bash
eslint --fix ./*.ts
```

**What did you expect to happen?**

I expected the fix to occur as below:

```ts
const getObject = () => ({ huge: ['sized'], dynamic: ['object'] });

const obj = { ...getObject() };
console.log(obj);
```

**What actually happened? Please include the actual, raw output from ESLint.**

Actual output code:

```ts
const getObject = () => ({ huge: ['sized'], dynamic: ['object'] });

const obj = <{}, Record<string, string[]>>{ ...getObject()};
console.log(obj);
```

This repository can reproduce the above problem: [kurone-kito/example-for-eslint-POS](https://github.com/kurone-kito/example-for-eslint-POS)

**Are you willing to submit a pull request to fix this bug?**

Probably no, because I don't know the cause.
