### ISSUE TITLE
Rule for max-len failing for line under the length limit

### ISSUE THREAD

**Issue by tgrass12** [eslint/eslint#13799]
**Tell us about your environment**

Node version: v14.14.0
npm version: v6.14.8
Local ESLint version: v7.12.0 (Currently used)
Global ESLint version: Not found

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
Whichever is used by `create-react-app` (`@babel/eslint-parser`?).
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - react-app
  - prettier
  - airbnb-base
parserOptions:
  ecmaVersion: 12
ignorePatterns:
  - serviceWorker.js
overrides:
  - files:
      - "*.test.js"
    rules:
      no-unused-vars: 0
rules:
  no-underscore-dangle: 1
  no-plusplus:
    - 1
    - allowForLoopAfterthoughts: true
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
        - "**/*.test.js"
        - src/setupTests.js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const nutrientTotals = nutrition.mealOccasions.map((mealOccasion) => {
  return mealOccasion.foods.map((food) => {});
});

```

```bash
npx eslint --cache --fix --config .eslintrc.commit.yml .
```

**What did you expect to happen?**
Linter should find no issues
**What actually happened? Please include the actual, raw output from ESLint.**
  `1:1    error  This line has a length of 107. Maximum allowed is 100             max-len`

It seems the rule is reading up to the closing parenthesis after the variable within the inner map, spaces removed.
```js
`const nutrientTotals = nutrition.mealOccasions.map((mealOccasion) => {
return mealOccasion.foods.map((food`.length
// prints 107
```

Running the linter again with a different variable name seems to confirm this as well:
```js
const nutrientTotals = nutrition.mealOccasions.map((mealOccasion) => {
  return mealOccasion.foods.map((someLongerVariable) => {});
});
```
`  1:1    error  This line has a length of 121. Maximum allowed is 100             max-len`
```js
`const nutrientTotals = nutrition.mealOccasions.map((mealOccasion) => {
return mealOccasion.foods.map((someLongerVariable
`.length
// prints 121
```
