### ISSUE TITLE
ESLint erroneously tries to validate contents of String.raw if it contains jsx

### ISSUE THREAD

**Issue by ericvergnaud** [eslint/eslint#14094]
**Tell us about your environment**

WebStorm 2020.3.2
Build #WS-203.7148.54, built on January 25, 2021
Memory: 2500M

* **ESLint Version:**
Local ESLint version: v7.11.0 (Currently used)
* **Node Version:**
Node version: v14.13.0
* **npm Version:**
npm version: v7.4.0
yarn 1.22.10
* **Operating System:** 
macOS 10.16

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
parser: babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

package.json fragment
```json
 {
 "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-proposal-dynamic-import": "^7.10.4",
    "@babel/plugin-transform-modules-amd": "^7.10.5",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.10.4",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.3.0",
    "babel-loader": "^8.1.0",
    "eslint": "^7.9.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-es5": "^1.5.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.1.3",
    "eslint-plugin-react": "^7.21.4",
    "jest": "^26.6.3",
    "react": "^16.12.0",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^16.12.0",
    "react-scripts": "^2.1.8",
    "terser-webpack-plugin": "^4.2.2",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.12",
    "webpack-conditional-loader": "^1.0.12"
  }
}
```
.eslintrc.yml
```yaml
env:
  browser: true
  es6: true
  node: true
  amd: true
  jest/globals: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - es5
  - react
  - jest
rules:
  no-unused-vars: ["error", {vars: "all", args: "none"}]
  no-prototype-builtins: [ "off" ]
  no-fallthrough: ["error", { "commentPattern": "no-break" }]
  react/jsx-uses-vars: 1
  import/no-webpack-loader-syntax: [ "off" ]
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const data = String.raw`
return x <div>
            <AccountsNavbar/>
            <AccountsTable visible={state.view == "Accounts"} />
            <UsersTable visible={state.view == "Users"} />
            <OrganizationsTable visible={state.view == "Organizations"} />
        </div>;
`;
```
note the ```x``` in the above, this is intentional

command is built into web storm

**What did you expect to happen?**
no error should be raised

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
dozens of syntax errors   

**Steps to reproduce this issue:**
1. Create a WebStorm project 
2. Configure usage of ESLint
3. Create a js file containing the above code 

**Are you willing to submit a pull request to fix this bug?**
Why not but I wouldn't know where to start
