### ISSUE TITLE
new-cap should allow defining exceptions

### ISSUE THREAD

**Issue by liebrand** [eslint/eslint#1424]
See : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

Basically, it would be great if new-cap could ignore DateTimeFormat as well. 

Alternatively, it might be even more flexible if the new-cap rule could have an option array of additional modules that the client could add to be ignored.

**Comment by fearphage** [comment]
Is this fixed? Based on [the tests](https://github.com/eslint/eslint/blob/master/tests/lib/rules/new-cap.js#L54), this seems like what I want:

```` yaml
rules:
  new-cap: 
    capIsNew: true
    capIsNewExceptions: 
      - 'Polymer'
````

This isn't working. Am I just missing something?
