### ISSUE TITLE
yml validate issue

### ISSUE THREAD

**Issue by Mister-Hope** [eslint/eslint#14547]
**Tell us about your environment**

Node version: v14.16.1
npm version: v7.7.6
Local ESLint version: v7.25.0
Global ESLint version: Not found
Operating System: win32 10.0.19042

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

@babel/eslint-parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

parser: '@babel/eslint-parser'

settings:
  react:
    version: detect

ignorePatterns:
  - dist/
  - node_modules/

overrides:
  - files:
      - 'packages/admin/**/*.js'

    extends:
      - plugin:react/recommended

    parserOptions:
      ecmaVersion: 11
      sourceType: module

    env:
      browser: true

    globals:
      think: readonly

    rules:
      react/display-name: off
      react/prop-types: off

  - files:
      - 'packages/client/**/*.js'

    extends:
      - plugin:react/recommended

    parserOptions:
      ecmaVersion: 11
      sourceType: module

    env:
      browser: true

    globals:
      VERSION: readonly

    rules:
      react/prop-types: off

  - files:
      - 'packages/cloudbase/**/*.js'

    globals:
      think: readonly

  - files:
      - 'packages/server/**/*.js'

    globals:
      think: readonly

  - files:
      - 'packages/**/__tests__/**/*.spec.js'

    env:
      jest: true

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Nothing

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

[Error - 下午1:55:16] Error: ESLint configuration in F:\npm\waline\\.eslintrc.yml is invalid:
	- Unexpected top-level property "ignorePatterns".

    at validateConfigSchema (F:\npm\waline\packages\server\node_modules\eslint\lib\config\config-validator.js:221:15)
    at Object.validate (F:\npm\waline\packages\server\node_modules\eslint\lib\config\config-validator.js:238:5)
    at loadFromDisk (F:\npm\waline\packages\server\node_modules\eslint\lib\config\config-file.js:516:19)
    at Object.load (F:\npm\waline\packages\server\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getLocalConfigHierarchy (F:\npm\waline\packages\server\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (F:\npm\waline\packages\server\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (F:\npm\waline\packages\server\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (F:\npm\waline\packages\server\node_modules\eslint\lib\config.js:329:29)
    at processText (F:\npm\waline\packages\server\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (F:\npm\waline\packages\server\node_modules\eslint\lib\cli-engine.js:620:17)
