### ISSUE TITLE
ES6 rest args triggers warnings

### ISSUE THREAD

**Issue by zpao** [eslint/eslint#1543]
This code
```js
"use strict";
module.exports.b = function foo(...args) {
  return args;
};
```

With this config
```yaml
settings:
  ecmascript: 6
env:
  node: true
rules:
  block-scoped-var: 1
```

Results in this
```
eslint-test.js
  2:35  warning  "args" used outside of binding context  block-scoped-var
  3:9   warning  "args" used outside of binding context  block-scoped-var
  3:9   error    'args' is not defined                   no-undef

✖ 3 problems
```

The obvious problem here is that rest args just aren't supported in these rules. (v0.11.0-alpha.0)
