### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'getFirstToken') as of ESLint 8.40.0

### ISSUE THREAD

**Issue by yktoo** [eslint/eslint#17279]
### Environment

Node version: 18.16.0
npm version: 9.5.1
Local ESLint version: 8.42.0
Global ESLint version: n/a
Operating System: Ubuntu 23.04 / amd64

### What parser are you using?

Default (Espree)

### What did you do?

ESLint fails to parse the code with:

```
Message:
    Cannot read properties of undefined (reading 'getFirstToken')
Occurred while linting /home/dk/code/GitLab/comentario/comentario/embed/src/api.ts:48
Details:
    currentNode: [object Object]
    domainEmitter: [object Object]
    domainThrown: false
```

It errors with every version starting 8.40.0, doesn't happen with 8.39.0 and earlier.

The referenced code (`api.ts:48`) is a class export:

```ts
export class ApiService {
...
```

The code to reproduce is [this commit](https://gitlab.com/comentario/comentario/-/commit/addd7904e89747fdc384c3c26e9cbfb3f8e5ebf7): the version of `eslint` in `package.json` needs to be raised to 8.40+, then `yarn install`, then ESLint can be run with:

```bash
npm run build -w embed
```

### What did you expect to happen?

A successful execution.

### What actually happened?

ESLint fails to parse the code.

### Link to Minimal Reproducible Example

https://gitlab.com/comentario/comentario/-/commit/addd7904e89747fdc384c3c26e9cbfb3f8e5ebf7

### Participation

- [ ] I am willing to submit a pull request for this issue.
