### ISSUE TITLE
Change Request: (add eslint warnings exit code)

### ISSUE THREAD

**Issue by alSergey** [eslint/eslint#18402]
### ESLint version

v8.57.0

### What problem do you want to solve?

We have a fe eslint job in GitLab CI that runs eslint checks. Currently there is no way to show a warning in a job if eslint ends with a warning.

### What do you think is the correct solution?

Add a new exit code, which will be triggered if eslint checks find 0 error and more than 0 warning.

```yaml
fe eslint:
  script:
    - npx eslint .
   allow_failure:
      exit_codes: X
```

### Participation

- [ ] I am willing to submit a pull request for this change.
