### ISSUE TITLE
destructuring doesn't work with block-scoped-var

### ISSUE THREAD

**Issue by carlosrocha** [eslint/eslint#1863]
.eslintrc

```yaml
---
  ecmaFeatures:
    destructuring: true

  rules:
    block-scoped-var: 2
```

test.js
```javascript
function myFunc(foo) {
  "use strict";
  var { bar } = foo;

  bar.hello();
}

myFunc();
```

Error:
```
test.js
  5:2  error  "bar" used outside of binding context  block-scoped-var

✖ 1 problem (1 error, 0 warnings)
```
