### ISSUE TITLE
Bug: There was a problem loading formatter

### ISSUE THREAD

**Issue by luisaveiro** [eslint/eslint#18813]
### Environment

Node version: v20.16.0
npm version: 10.8.1
Local ESLint version: ^9.9.0
Global ESLint version: 
Operating System: Ubuntu 22.04.4 (GitHub Actions)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I attempted to run ESLint v9 as part of a GitHub Actions workflow in my project. The workflow is configured to lint the codebase on every push to the repository using the latest version of ESLint.

<details>
<summary>Configuration</summary>

```ts
import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';

export default [
  { files: ['**/*.{js,mjs,cjs,ts}'] },
  { languageOptions: { globals: { ...globals.browser, ...globals.node } } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  eslintPluginPrettierRecommended,
];

```
</details>

<details>
<summary>Package.json</summary>

In my `package.json`, I have the following scripts:

```js
  "scripts": {
    "lint": "eslint .",
    "lint:fix": "yarn run lint --fix",
  },
```
</details>

<details>
<summary>GitHub Actions</summary>

```yaml
name: Format code

description: Format code with formatters and linters.

runs:
  using: 'composite'
  steps:
    - name: Run ESLint
      shell: bash
      working-directory: ${{ env.working-directory }}
      run: yarn run lint:fix

    - name: Run Prettier
      shell: bash
      working-directory: ${{ env.working-directory }}
      run: yarn run format:style
```

</details>

### What did you expect to happen?

I expected ESLint v9 to run successfully during the GitHub Actions workflow, and fix linting as usual, without any errors or interruptions.

### What actually happened?

When the workflow reached the step where ESLint v9 was supposed to run, it threw an error (details of the error are provided below). This caused the workflow to fail, preventing the linting process from completing.

```
There was a problem loading formatter: /home/runner/work/vite-typescript-package-toolkit/vite-typescript-package-toolkit/code/node_modules/eslint/lib/cli-engine/formatters/stylish.js
Error: require() of ES Module /home/runner/work/vite-typescript-package-toolkit/vite-typescript-package-toolkit/code/node_modules/strip-ansi/index.js from /home/runner/work/vite-typescript-package-toolkit/vite-typescript-package-toolkit/code/node_modules/eslint/lib/cli-engine/formatters/stylish.js not supported.
Instead change the require of index.js in /home/runner/work/vite-typescript-package-toolkit/vite-typescript-package-toolkit/code/node_modules/eslint/lib/cli-engine/formatters/stylish.js to a dynamic import() which is available in all CommonJS modules.
```

### Link to Minimal Reproducible Example

https://github.com/wolfpackthatcodes/vite-typescript-package-toolkit/actions/runs/10546227297/job/29217438284?pr=196

### Participation

- [ ] I am willing to submit a pull request for this issue.
