### ISSUE TITLE
[feature request] Enforce Dangling Commas (comma-dangle) only in multiline array/object literals

### ISSUE THREAD

**Issue by UltCombo** [eslint/eslint#1984]
As title says, I'd like this code to lint:

```js
var arr = [
    1,
    2,
];
var obj = {
    a: 1,
    b: 2,
};
var arr2 = [1, 2];
var obj2 = { a: 1, b: 2 };
```

And the following patterns to fail linting:

```js
var arr = [
    1,
    2
];
var obj = {
    a: 1,
    b: 2
};
var arr2 = [1, 2,];
var obj2 = { a: 1, b: 2, };
```

Is this possible to implement as an option to `comma-dangle`?

Thanks.

**Comment by nzakas** [comment]
This isn't possible today, but shouldn't be too hard to add.

**Comment by UltCombo** [comment]
Thanks for the quick triaging.

I've been thinking about more complex use cases (e.g. mixed style, multiline array/object literals with some properties in the same line), and I believe the logic could be kept rather simple: only allow (and require) a trailing comma when there is a newline between the last item/property and the closing `]`/`}` respectively.

WDYT?

**Comment by nzakas** [comment]
I'm a bit confused by that wording. What I was thinking was to have an option "always-multiline" that enforces dangling commas only when the array or object literal is on multiple lines.

**Comment by UltCombo** [comment]
> What I was thinking was to have an option "always-multiline" that enforces dangling commas only when the array or object literal is on multiple lines.

Yes, that wording is clearer indeed. `=]`

**Comment by keithamus** [comment]
Just FYI, [JSCS offers this feature](http://jscs.info/rules.html#requiretrailingcomma) as `"requireTrailingComma": { "ignoreSingleLine": true }`

Similarly there is a plugin available in the eslint ecosystem; [eslint-plugin-require-trailing-comma](https://github.com/greggman/eslint-plugin-require-trailing-comma). This plugin has the following modes:

```yml
# No trailing comma is required
require-trailing-comma/require-trailing-comma: 0

# Multiline Objects or Arrays must have a trailing comma
require-trailing-comma/require-trailing-comma: 2

# Every Object or Array (including single lines) must have a trailing comma
require-trailing-comma/require-trailing-comma: [2, "all"]
```

As a workaround for now - you can simply set `comma-dangle: 0` and use [eslint-plugin-require-trailing-comma](https://github.com/greggman/eslint-plugin-require-trailing-comma) instead.
