### ISSUE TITLE
"no-console" is ignored on "node" environment

### ISSUE THREAD

**Issue by mickaeltr** [eslint/eslint#2021]
Hello,

I would like to disable the use of the global console object, on Node.js applications. But the "no-console" rule is ignored on "node" environment.

Is there a workaround?

Thanks :)

**Comment by nzakas** [comment]
It isn't ignored, it's off by default. You can just turn it back on.

```yaml
env:
  node: true
rules:
  no-console: 2
```
