### ISSUE TITLE
`Unexpected token ILLEGAL` when using ES6 template strings in JSX props

### ISSUE THREAD

**Issue by lencioni** [eslint/eslint#2045]
With the following file:

```jsx
const React = require('react/addons');
const Test = require('test');

var namePart = 'testing';
var test = <Test name={`name${namePart}`} />;

module.exports = test;
```

I get the following output:

> tmp.jsx
>   8:1  error  Unexpected token ILLEGAL
> 
> ✖ 1 problem (1 error, 0 warnings)

ESLint 0.17.0.

Heres a bit of my configuration file:

```yaml
  env:
    browser: true
    es6: true
    node: true

  ecmaFeatures:
    jsx: true
```

Am I doing something wrong here? Let me know if you need any more information.
