### ISSUE TITLE
eslint-disable-line directive still errors for exceeding max-len

### ISSUE THREAD

**Issue by kentor** [eslint/eslint#2074]
```javascript
1; // eslint-disable-line
```

```yaml
---
rules:
  max-len: [2, 1]
```

```bash
index.js
  1:0  error  Line 1 exceeds the maximum line length of 1  max-len

✖ 1 problem (1 error, 0 warnings)
```

Expected the directive to allow exceeding max-len rule.
