### ISSUE TITLE
no-undef does not check Node.js scope for variables used in JSX

### ISSUE THREAD

**Issue by yannickcr** [eslint/eslint#2093]
no-undef does not check Node.js scope for variables used in JSX

test.js

```javascript
var App = require('App');

module.exports = <App />
```

.eslintrc

```yaml
env:
    node: true
ecmaFeatures:
    jsx: true
rules:
    no-undef: 2
```

Output:

```bash
test.js
  3:18  error  'App' is not defined                                                 no-undef

✖ 1 problem (1 error, 0 warnings)
```
