### ISSUE TITLE
func-names with ES6 classes

### ISSUE THREAD

**Issue by Marsup** [eslint/eslint#2103]
ESLint seems to misunderstand ES6 classes definitions.

test.js :
```js
class A {
  constructor() {}
  foo() {}
}
```

.eslintrc
```yaml
ecmaFeatures:
  classes: true
rules:
  func-names: 2
```

Errors :
```
test.js
  2:13  error  Missing function expression name  func-names
  3:5   error  Missing function expression name  func-names
```
I can make probably make a patch but I don't know if the problem is in the parser or in ESLint.
