### ISSUE TITLE
Unused variable warning in JSX files

### ISSUE THREAD

**Issue by rylanc** [eslint/eslint#2156]
When a variable is only used in a JSX tag expression, I'm getting a `no-unused-vars` warning. My rule config is set to
```json
"no-unused-vars": [1, {
  "vars": "all",
  "args": "none"
}],
```

Here's an example of the warning:
```js
var React = require('react');
var Text = require('./Text'); // "Text is defined but never used  no-unused-vars"

var Test = React.createClass({
  render: function() {
    return (
      <Text>Hello</Text>
    );
  }
});

module.exports = Test;
```

**Comment by BenoitZugmeyer** [comment]
Since [0.17.0](http://eslint.org/blog/2015/03/eslint-0.17.0-released/), you have to use [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) to mark JSX variables as used.

**Comment by nzakas** [comment]
Please see discussion in #1911.

**Comment by macgyver** [comment]
Sorry to bring it up again but this is still an issue for me.

Steps to reproduce
- install `eslint` and `eslint-plugin-react` globally
- build an eslint config file via `eslint --init` and include react and jsx, I can paste the entire file if you like but the top of the config file looks like this: 
```
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
```
- run the tool on a simple jsx file
```
$ cat demo.js
import Foo from 'foo.jsx';
export default <Foo/>;
$ eslint demo.js

demo.js
  1:8  error  'Foo' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

Am I missing something obvious?
