### ISSUE TITLE
TypeError: Object #<Object> has no method 'forEach' when plugins section is in .eslintrc

### ISSUE THREAD

**Issue by kevinold** [eslint/eslint#2209]
I am using eslint v0.18.0 on node v0.10.38 and wish to use https://github.com/yannickcr/eslint-plugin-react.  When I specify the "react" plugin in my .eslintrc:

```
env:
    node: true
    browser: true
    jquery: true

plugins:
    react: true

globals:
    jQuery: true
    jest: true
    describe: true
    xdescribe: true
    it: true
    xit: true
    spyOn: true
    expect: true
    beforeEach: true

ecmaFeatures:
    jsx: true

rules:
    strict: [2, "never"]
    no-underscore-dangle: 0
    quotes: 0
    new-cap: 0
    key-spacing: 0
    dot-notation: 0
```

When I run "eslint ." I receive this error:
```
/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util.js:43
            property.forEach(function (plugin) {
                     ^
TypeError: Object #<Object> has no method 'forEach'
    at /Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util.js:43:22
    at Array.forEach (native)
    at Object.mergeConfigs (/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util.js:35:25)
    at Config.getConfig (/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/config.js:289:19)
    at processFile (/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/cli-engine.js:174:27)
    at /Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/cli-engine.js:293:26
    at /Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/kevinold/.nvm/v0.10.38/lib/node_modules/eslint/lib/util/traverse.js:83:9)
```

I do not receive an error when I run via the command line:

`eslint --plugin react app/assets/javascripts`
