### ISSUE TITLE
no-multiple-empty-lines fails on last blank line

### ISSUE THREAD

**Issue by PhilT** [eslint/eslint#2359]
If you set this rule to only allow one blank line, it incorrectly reports the final blank line as failing this rule.

For example:

        1 'use strict';
    >>  2   

My `.eslintrc` file

```
---
  env:
    browser: true
    node: true
    jasmine: true
    phantomjs: true

  globals:
    FB: true
    gon: true
    fbInitialized: true
    config: true

  rules:
    no-cond-assign:
      - 1
      - always
    no-extra-parens: 1
    valid-jsdoc: 1

    block-scoped-var: 1
    complexity:
      - 1
      - 5
    no-param-reassign: 1
    no-self-compare: 1
    no-void: 1
    vars-on-top: 1
    wrap-iife: 1
    strict:
      - 2
      - global

    indent:
      - 2
      - 2
    brace-style:
      - 2
      - 1tbs
      - allowSingleLine: true
    camelcase: 2
    comma-spacing: 2
    comma-style: 2
    consistent-this:
      - 2
      - self
    func-style:
      - 2
      - expression
    max-nested-callbacks:
      - 2
      - 3
    newline-after-var: 2
    no-continue: 2
    no-inline-comments: 2
    no-lonely-if: 2
    no-multiple-empty-lines:
      - 2
      - max: 1
    no-nested-ternary: 2
    no-new-object: 2
    no-trailing-spaces: 2
    operator-assignment:
      - 2
      - always
    operator-linebreak: 2
    padded-blocks:
      - 2
      - never
    quote-props:
      - 2
      - as-needed
    quotes:
      - 2
      - single
      - avoid-escape
    space-after-keywords: 2
    space-before-blocks: 2
    space-before-function-paren:
      - 2
      - anonymous: always
        named: never
    space-in-brackets: 2
    space-in-parens: 2

```
