### ISSUE TITLE
`comma-dangle` `always-multiline` triggers no warning

### ISSUE THREAD

**Issue by pascalduez** [eslint/eslint#2406]
```js
var foo = {
  bar: "baz",
  qux: "quux"
};

var foo = { bar: "baz", qux: "quux", };
``` 

``` yaml
#.eslintrc
rules:
  comma-dangle: "always-multiline"

``` 

```json
  "version": "0.20.0",
```

Result: no warning returned.
