### ISSUE TITLE
Unexpected token for spread operator.

### ISSUE THREAD

**Issue by ayrton** [eslint/eslint#2532]
``` js
// app/assets/javascripts/currentUser.js
variable = {
  a: 'a',
  b: 'b'
}

export default {
  toJSON: function() {
    return {...variable};
  }
};
```

Currently throws an unexpected token while this is a valid syntax.

``` sh
$ eslint app/assets/javascripts/currentUser.js

app/assets/javascripts/webpack/currentUser.js
  8:13  error  Unexpected token ..

✖ 1 problem (1 error, 0 warnings)
```

I did this on a fresh `npm install eslint`.

**Comment by hzoo** [comment]
So this is https://github.com/sebmarkbage/ecmascript-rest-spread ES7 and ESLint isn't supporting it at the moment? Duplicate of #2352.

**Comment by ilyavolodin** [comment]
@hzoo is correct. We do not support object spread.

**Comment by 3den** [comment]
any update about this? I saw on the docs that i can add `spread: true` but it still gives me the same error. I am using eslint 2.8.0 and below is mine .eslintrc.yml

```yaml
extends: "eslint:recommended"

env:
  browser: true
  es6: true
  jasmine: true

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    spread: true
```
