### ISSUE TITLE
Can't disable an env in a single file

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint#2614]
I've got a project all written in ES6, except for a single file that is in ES5.

In my .eslintrc:

```yaml
env:
  es6: true
  node: true
  browser: true
```

In the single ES5 file:

```js
/*eslint-env es6:false*/

const fn = () => {};
```

I expected to get an eslint error for the fat arrow, but there's no error.
