### ISSUE TITLE
Disable rules for given identifiers

### ISSUE THREAD

**Issue by tlvince** [eslint/eslint#2620]
Is it possible to disable rules for given identifiers? For example, in CouchDB projects, I'm forced to scatter `/*eslint-disable no-underscore-dangle */` comments on every instance of `_id` or `_rev` as I'd otherwise like to keep this rule enabled globally.

Could this be part of a rule's configuration? Perhaps:

```yml
rules:
  no-underscore-dangle:
    - 2
    - disable:
      - _id
      - _rev
```
