### ISSUE TITLE
Cannot specify boolean .eslintrc values with 0.23.0

### ISSUE THREAD

**Issue by hatched** [eslint/eslint#2818]
On OSX 10.10.3 using the following `.eslintrc` it will correctly run when using `0.22.1` but fails with the following error using `0.23.0`. The same issue appears using a yaml or json .eslintrc file, global and locally installed bin's.

```yaml
env:
  browser: true
  node: true
rules:
  quotes: [2, "single"]
  camelcase: true
```

```
/usr/local/lib/node_modules/eslint/lib/config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: /<path>/.eslintrc:
	Configuration for rule "camelcase" is invalid:
	Value "true" is the wrong type.
```
*`<path>` substituted for real path
