### ISSUE TITLE
Infix operator error in jsx ternary

### ISSUE THREAD

**Issue by aabenoja** [eslint/eslint#3016]
I'm getting an `Infix operators must be spaced` error on the following ternary:

```jsx
let optionalComponent = this.props.someOptionalVal ? (
  <span>
    {this.props.someOptionalVal}
  </span>
) : null;
```

We have a couple of places where we use ternaries like this to choose whether to generate an optional item or assign a `null` in its place. There error is being thrown on the colon before `null`.

**Comment by michaelficarra** [comment]
Did you mean to file this against espree instead?

**Comment by Jackyjjc** [comment]
same here with `something.prop ? (d.something || 'blah') : d.something`

giving me Infix operators must be spaced. This is in node.js with the latest version of eslint installed from npm

**Comment by nzakas** [comment]
Thanks for the report. Can you please provide:

1. The exact version of ESLint you are using
2. The config for the rule
3. The complete ESLint output

**Comment by Jackyjjc** [comment]
The version i fall back to but it is still failing is eslint@0.22.1

```
parser: babel-eslint
environment:
  node: true
  mocha: true
ecmaFeatures:
  generators: true
  modules: true
  blockBindings: true
rules:
  semi: 2
  quotes: [2, "single"]
  max-len: [2, 120]
  no-undef: 0
  strict: 0
  no-extra-strict: 0
  no-use-before-define: 0
  space-unary-ops: 0
  curly: 0
  no-underscore-dangle: 0
  new-cap: [2, {"capIsNew": false}]
  new-parens: 0
  no-extend-native: 0
```

```
> eslint .

xxx/xxx/xxx.js
  78:76  error  Infix operators must be spaced  space-infix-ops

✖ 1 problem (1 error, 0 warnings)


npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/jchen/xxx/xxx/node_modules/.bin/npm" "run" "lint"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the  lint script 'eslint .'.
npm ERR! This is most likely a problem with the xxx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!    eslint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls xxx
npm ERR! There is likely additional logging output above.
```
