### ISSUE TITLE
no-undef errors incorrectly if function is defined within block and block binding is enabled

### ISSUE THREAD

**Issue by bgw** [eslint/eslint#3130]
```js
var foo = true;

if (foo) {
  function bar() { console.log('hey'); }
}

if (foo) {
  bar();
}
```

gives

![screen shot 2015-07-22 at 11 50 43 am](https://cloud.githubusercontent.com/assets/180404/8834246/f0911ff8-3067-11e5-9d27-a7ec41c2de44.png)

When using espree with `blockBindings: true` or babel-eslint.

```yaml
---
parser: espree
ecmaFeatures:
  blockBindings: true
rules:
  no-undef: 2
env:
  node: true
```

It seems related to [this bit of code in escope](https://github.com/estools/escope/blob/dd36f30eb8b23bae1bc6ff58bf086349b954c1df/src/referencer.js#L587).
