### ISSUE TITLE
Proposal: Simplified configuration

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3626]
**Problem:** We're getting more complaints about the severity code (0, 1, 2) in configuration files. While I personally don't see this as a big problem, and people do seem to get used to it, it's still confusing to new users. 

**Proposal:** We augment configuration with some additional options. In addition to `rules`, we introduce `warnings` and `errors`, so you can place a rule directly into the group you want it in. Usage would entail:

1. A rule ID can be set to `true` to enable in that severity. If the rule has options, then providing the options (array, string, object) is equivalent to `true`.
1. A rule ID can be set to `false` to disable it in that severity.
1. Priority goes in order of: `errors`, `warnings`, and `rules`. That means the setting in `errors` overrides everything else, and `warnings` overrides `rules`.

What it would look like:

```yaml
rules:
    indent: [2, 4]
warnings:
    indent: false        # actually, turn off indent
    semi: "always"
errors:
    quotes: "double"
    semi: "never"      # actually, we should never use semicolons
```

We would also then have to introduce some new inline comments, like:

```js
/*eslint-errors indent: 4, semi: "never"*/
/*eslint-warnings indent: 4, semi: "never"*/
```

**Implementation:** In order to keep things simple, we could just augment configurations as they come, pulling out `errors` and `warnings`, converting their options to an array and prepending the correct severity code. Basically, preprocess new-style configs into old-style configs and then let the old-style configs flow through the rest of ESLint.

**Points to investigate:**

1. If we have any rules whose option is simply a boolean value, as that would clash with this proposal. If yes, then we'd need to update that rule(s) so it doesn't accept a boolean value.
1. Is it confusing to be able to accidentally put the same rule in more than one section? Do we need some sort of validation to prevent that?
1. Does the preprocessing of configs have a significant performance impact?

**Comment by ilyavolodin** [comment]
This is in regards to point 2.
```yaml
rules:
    indent: [0,4]
warnings:
    indent: true
errors:
    indent: true
```

What's the expected behavior of the example above?
Sorry, I'm not sure I like this proposal. If I remember correctly your argument to proposal to replace [0,1,2] with string values ['off', 'warning', 'error'] was that you don't want arbitrary strings in configuration. How is having arbitrary strings as section names any different?
I agree that 0,1,2 might be confusing to new users. I'm just not sure I see a better solution.
