### ISSUE TITLE
Bug: Indent callback function

### ISSUE THREAD

**Issue by ChristianMurphy** [eslint/eslint#4165]
**Eslint Version**
1.7.0

**Eslint configuration**
``` yaml
rules:
    indent:
        - 2
        - 4
        - SwitchCase: 1
```

**Source Code**
``` js
function example (callback) {
    callback();
}

example(
    function () {
        console.log('example');
    }
);
```

**Errors**
```
7:9  error  Expected indentation of 4 space characters but found 8  indent
8:5  error  Expected indentation of 0 space characters but found 4  indent
```

**Expected**
No Errors

**Note**
Eslint 1.6.0 does not print errors for this code.
