### ISSUE TITLE
plugin w/ custom rule: what am I doing wrong?

### ISSUE THREAD

**Issue by boneskull** [eslint/eslint#4627]
Given [this package](/boneskull/eslint-plugin-prototype-chain), running ESLint after installing it results in this:

```
 1:1  warning  Definition for rule 'prototype-chain' was not found  prototype-chain
```

Here's my `.eslintrc`:

```yaml
---
plugins:
  - prototype-chain

parser: babel-eslint

rules:
  space-before-function-paren: 0
  arrow-parens:
    - 1
    - as-needed
  prototype-chain: 1
```
