### ISSUE TITLE
TAP formatter only display one message per file.

### ISSUE THREAD

**Issue by SimonDegraeve** [eslint/eslint#4975]
Version :
`1.10.3`

File to lint : 
```
var a = 'foo';
var b = 'bar';
```

Configuration : 

```
{
  "extends": "airbnb"
}
```

Result with default formatter: 

```
/my/path/test.js
  1:1  error  Unexpected var, use let or const instead  no-var
  1:5  error  "a" is defined but never used             no-unused-vars
  2:1  error  Unexpected var, use let or const instead  no-var
  2:5  error  "b" is defined but never used             no-unused-vars

✖ 4 problems (4 errors, 0 warnings)
```

Result with TAP formatter: 

```
TAP version 13
1..1
not ok 1 - /my/path/test.js
  ---
  message: 'Unexpected var, use let or const instead.'
  severity: error
  data:
    line: 1
    column: 1
    ruleId: no-var
  messages:
    - message: '"b" is defined but never used'
      severity: error
      data:
        line: 2
        column: 5
        ruleId: no-unused-vars
  ...
```

Problem: 

The TAP formatter swallow messages and only display the first and the last one.
