### ISSUE TITLE
[rule: no-shadow] false positive caused by a path string

### ISSUE THREAD

**Issue by lucendio** [eslint/eslint#5450]
**What version of ESLint are you using?**
2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
Espree

**What did you do? Please include the actual source code causing the issue.**

ESLint config excerpt:
```yaml
no-shadow: [
    2,
    {
        builtinGlobals: true,
        hoist: 'functions',
        allow: []
    }
]
```
js file content:
```js
const path = '/account/:name';
let name = 'unimportant value';
```

**What did you expect to happen?**
variable declaration of ``name``(line:2) doesnt get marked as a problem

**What actually happened? Please include the actual, raw output from ESLint.**
variable declaration of ``name``(line:2) gets marked as a problem

**output message (within webstorm)**
``ESLint: 'name' is already declared in the upper scope. (no-shadow)``

 My guess: regex for finding a previous usage needs a bit more work
