### ISSUE TITLE
`consistent-return` Treat `return void ...` the same as `return;`

### ISSUE THREAD

**Issue by scriptdaemon** [eslint/eslint#6026]
**What version of ESLint are you using?**

2.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

```
root: true

env:
  es6: true
  node: true

extends:
  "eslint:recommended"

rules:
  consistent-return: "error"
```

**What did you do? Please include the actual source code causing the issue.**

Wrote a function with a callback that returns early when an error is found:

```js
log(level, message, meta, callback) {
  let recipientId = _.get(meta, 'recipientId');
  if (!recipientId) {
    return void callback(new Error('No recipient ID'));
  }

  // Other code that doesn't return anything ...
}
```

Returning the callback is nice because it saves a line, but I want to guarantee the function returns nothing (thus the use of `void`).

**What did you expect to happen?**

No error.

**What actually happened? Please include the actual, raw output from ESLint.**

` error  Expected to return a value at the end of this method  consistent-return`
