### ISSUE TITLE
Configuration to enable all rules

### ISSUE THREAD

**Issue by mockdeep** [eslint/eslint#6240]
I would love to have a configuration that enables all rules, that way I can selectively disable them:

```yml
extends: ['eslint:all']
```

This way I can easily be made aware of new rules when I upgrade, and don't have to go hunting through the docs to figure out which ones to add to my configuration file.

**Comment by mysticatea** [comment]
Related: #2730.

**Comment by mockdeep** [comment]
Oh, okay. Should I comment there instead? I hacked together a basic script which does it, but it would be great to have something out-of-the-box. Needs some cleanup, but it did the trick:

```js
var _ = require('lodash');

var eslintRules = require('eslint/conf/eslint.json').rules;
var eslintEnabled = _.mapValues(eslintRules, function () { return 'error'; });

var reactRules = require('eslint-plugin-react').rules;
var disabledRules = {'react/jsx-sort-prop-types': true};
var reactEnabled = _.reduce(reactRules, function (result, value, key) {
  const ruleName = `react/${key}`;

  if (disabledRules[ruleName]) { return result; }
  result[ruleName] = 'error';

  return result;
}, {});

var allEnabled = _.extend({}, eslintEnabled, reactEnabled);

module.exports = { rules: allEnabled };
```

**Comment by nzakas** [comment]
We can discuss here. The concern with having all rules enabled is that not all of them have defaults that make sense for most people. For instance, people are generally split between double and single quotes, so what would you expect that rule to do when enabled by default? Maybe it doesn't matter, but I'm not sure. 

I'm not opposed to the idea, I just want to make sure we have a good idea of people's expectations around this.

**Comment by jfmengels** [comment]
If you want to familiarize yourself with all the rules by turning them on and seeing what kind of errors it shows in your codebase (and reading their doc file only when needed), you're better off copy-pasting the content of this file (https://github.com/eslint/eslint/blob/master/conf/eslint.json) (though I think it's a bit hidden) and setting everything to `error`.

If you want to find out about new rules easily, you can read the changelog or use tools like @sarbbottam's https://github.com/sarbbottam/eslint-find-rules.

For the rest, I agree with @nzakas that you need defaults for a few of these rules, and it doesn't make much sense to just turn them on like that.

**Comment by mockdeep** [comment]
To me it actually doesn't matter which one is the default. For my own part, I'm happy to go about reconfiguring things to suit my needs, but I want to have a simple way to be made aware of new rules, or rule changes, without having to go hunt them down in the changelog or elsewhere. It's easy to miss a new rule, also, for one reason or another, so unless I go to the pain of re-copying the default configuration and editing it, it's hard to be sure I'm aware of everything.

For me, it's about having as transparent and automatic a process as possible when upgrading to get the new rules enabled. If it's something that I'm already in line with, great! If not, I might make the changes on the fly or add it to the disabled list for now. If I always have to go back to find the new rules that are added or use a separate tool, it's more likely not to get done, and my code suffers for it. Not by any means arguing that it needs to be the default, but it would be nice to have an option to include all of them.

Another side effect of enabling all by default is that I have a much shorter configuration file (50 lines at the moment, including comments and react extension configuration), and instead of documenting all of the rules that are enabled, I have instead documented just the ones that depart from the default. This makes the file a little less overwhelming to look at, at least for me, and maybe a little more friendly to newcomers to a project.

```yaml
root: true
# have to include `plugin:react/recommended` for some reason to avoid errors
extends: ['./.eslint-all.js', 'plugin:react/recommended']
plugins: [react]
env:
  browser: true
  es6: true
  node: true
globals:
  $: true
ecmaFeatures:
  jsx: true
rules:
  # to enable someday
  'react/forbid-prop-types': [off]
  'react/no-multi-comp': [off]
  'react/no-set-state': [off]
  'react/no-string-refs': [off]
  'react/prefer-es6-class': [off]
  'react/prefer-stateless-function': [off]
  # departures from default
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  func-style: [error, declaration]
  id-length: [error, { exceptions: [_, $] }]
  indent: [error, 2]
  jsx-quotes: [error, prefer-single]
  max-len: [error, 115]
  max-statements-per-line: [error, { max: 2 }]
  max-statements: [error, { max: 14 }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  object-property-newline: [error, { allowMultiplePropertiesPerLine: true }]
  one-var: [error, never]
  padded-blocks: [error, never]
  prefer-arrow-callback: [error, { allowNamedFunctions: true }]
  quote-props: [error, as-needed, { keywords: true }]
  quotes: [error, single]
  space-before-function-paren: [error, { anonymous: always, named: never }]
  spaced-comment: [error, always, { markers: [=] }]
  'react/jsx-indent': [error, 2]
  'react/jsx-indent-props': [error, 2]
  'react/wrap-multilines': [error, { declaration: false }]
  # disabled
  init-declarations: [off]
  no-inline-comments: [off]
  no-magic-numbers: [off]
  no-ternary: [off]
  prefer-reflect: [off]
  require-jsdoc: [off]
  'react/jsx-handler-names': [off]
  'react/jsx-max-props-per-line': [off]
  'react/jsx-sort-props': [off]
```
