### ISSUE TITLE
/* in yaml comment actually acts as a multiline comment

### ISSUE THREAD

**Issue by austinhyde** [eslint/eslint#6545]
**What version of ESLint are you using?**

2.13.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

See below

**What did you do? Please include the actual source code causing the issue.**

```yaml
# adsf/*adsf
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

**What did you expect to happen?**

Lint with jsx/modules semantics

**What actually happened? Please include the actual, raw output from ESLint.**

Linted without jsx/modules semantics

```
$ ./node_modules/.bin/eslint .

path/to/my/file.js
  1:1  error  Parsing error: The keyword 'import' is reserved
...
```

I've been able to reproduce this 100% of the time in different configurations, and 100% of the time, it behaves like a multiline comment.

Bonus round:

```yaml
# adsf/*adsf
asdflk;jasdfjkl
# asdf*/asdf
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

lints correctly. Removing the first comment yields a configuration parse error, as you'd expect.

**Comment by mysticatea** [comment]
Thank you for this issue.

```yaml
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

There is no `modules: true` configuration for default parser. ([Specifying Parser Options](http://eslint.org/docs/user-guide/configuring#specifying-parser-options))
Please try `sourceType: "module"` instead.

```yaml
parserOptions:
  sourceType: "module"
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
```
