### ISSUE TITLE
`no-magic-number` and composed constants

### ISSUE THREAD

**Issue by dinoboff** [eslint/eslint#6647]
**What version of ESLint are you using?**
v3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```yaml
extends: eslint:recommended
env:
  es6: true
  node: true
parserOptions: 
  ecmaVersion: 6
  sourceType: script
rules:
  no-magic-numbers: error
```
**What did you do? Please include the actual source code causing the issue.**
index.js
```js
'use strict';

const ms = 1;
const second = ms * 1000;
const minute = second * 60;
const hour = minute * 60;
const day = hour * 24;

Object.assign(module.exports, {ms, second, minute, hour, day});
```

```shell
eslint index.js
```
**What did you expect to happen?**
No error.

**What actually happened? Please include the actual, raw output from ESLint.**

    path/to/index.js
      4:21  error  No magic number: 1000  no-magic-numbers
      5:25  error  No magic number: 60    no-magic-numbers
      6:23  error  No magic number: 60    no-magic-numbers
      7:20  error  No magic number: 24    no-magic-numbers

    ✖ 4 problems (4 errors, 0 warnings)
