### ISSUE TITLE
`max-len` rule `ignoreTemplateLiterals` not ignore multi-line template literals

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [eslint/eslint#7125]
**Tell us about your environment**

* **ESLint Version:** 3.5.0
* **Node Version:** 6.2.1
* **npm Version:** 3.9.6

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-eslint

**Please show your full configuration:** Isolated config and used only one rule.
```yaml
        "max-len": [
            2,
            100, {
                "ignoreComments": true,
                "ignoreTrailingComments": true,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignoreTemplateLiterals": true
            }
        ]
```

**What did you do? Please include the actual source code causing the issue.**
```js
        this.x = `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        aaaaaaaaaaaaa`;
```
![untitled](https://cloud.githubusercontent.com/assets/7084995/18440503/625bcbe8-78d7-11e6-9b40-9f9c07c4134b.png)

**What did you expect to happen?** I expected eslint to **not** throw a `max-len` error as I have **ignoreTemplateLiterals** turned on.

**What actually happened? Please include the actual, raw output from ESLint.** It threw an error for multi-line template literal.

/cc #5805 and #7049.
