### ISSUE TITLE
max-len config not working v3.9.1

### ISSUE THREAD

**Issue by vkbansal** [eslint/eslint#7556]
* **ESLint Version:** 3.9.1
* **Node Version:** 7.0.0
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESlint

```
rules:
    max-len:
        - 2
        - 120
        - code: 120
           ignoreString: true
           ignoreUrls: true
           ignoreTemplateLiterals: true
```

**What did you expect to happen?**
The lint should run

**What actually happened? Please include the actual, raw output from ESLint.**
```
/Users/vivek.bansal/Projects/my-project/.eslintrc.yml:
	Configuration for rule "max-len" is invalid:
	Value "[object Object]" no schemas match.
```

If I remove options, it works
```
rules:
    max-len:
        - 2
        - 120
```

**Comment by platinumazure** [comment]
According to the [docs](http://eslint.org/docs/rules/max-len#options), you can use either a numeric option or an object option, not both. The `code` object key is the same as the numeric option. So basically, you just need to remove the numeric option in your case. Hope this helps!

**Comment by vkbansal** [comment]
```
    max-len:
        - 2
        - code: 120
          ignoreString: true
          ignoreUrls: true
          ignoreTemplateLiterals: true
```

This also gives same error
