### ISSUE TITLE
"Parsing Error Unexpected Token" when destructuring object without using var 

### ISSUE THREAD

**Issue by aneilbaboo** [eslint/eslint#7832]
**Tell us about your environment**

* **ESLint Version:** v3.11.1
* **Node Version:** v7.2.0
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
Mainly es-lint, but also tried babel-eslint 6.12

**Please show your full configuration:**
```yaml
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
        experimentalObjectRestSpread: true
plugins:
  - mocha
rules:
  "strict": 0
  "no-unused-vars":
    - error
    - vars: all
       varsIgnorePattern: "^_$"
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - double
  semi:
    - error
    - always
  "mocha/no-exclusive-tests": error
```
**What did you do? Please include the actual source code causing the issue.**

```js
var a,b;

{a,b} = {a:1, b:2}; // parsing error at "= {a: 1"
```

**What did you expect to happen?**

This seems to be valid even in node v7.2.0 without babel.

**What actually happened? Please include the actual, raw output from ESLint.**
```shell
$ eslint sandbox/sandbox.js 

/Users/aneil/sandbox/sandbox.js
  3:8  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```
