### ISSUE TITLE
Type usage in for-of don't mark it as used.

### ISSUE THREAD

**Issue by dikmax** [eslint/eslint#8012]
**Tell us about your environment**

* **ESLint Version:** v3.14.1
* **Node Version:** v4.7.2
* **npm Version:** v2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?**
Parser Babel-eslint

**Please show your full configuration:**

```yaml
---
root: true
parser: babel-eslint

plugins:
  - meteor
  - eslint-comments
  - jsdoc
  - babel
  - flowtype
  - unicorn

extends:
  - airbnb-base
  - plugin:meteor/recommended

globals:
  # Flowtype special types
  Class: false
  HTTPResponse: false
  PointerEvent: false
  _jQuery_: false
  _jQueryEvent_: false
  $Diff: false
  $Shape: false
  $Record: false
  $Supertype: false
  $Subtype: false
  $Enum: false

settings:
  import/resolver: meteor
  jsdoc:
    tagNamePreference:
      returns: return
  flowtype:
    onlyFilesWithFlowAnnotation: false

rules:
  # Code complexity
  complexity: [warn, 15]
  max-nested-callbacks: [error, 3]
  max-statements-per-line:
    - error
    - max: 1
  max-statements: [warn, 30]
  max-params: [warn, 4]
  max-depth: [warn, 4]

  # Default overrides
  arrow-parens:
    - error
    - always
  capitalized-comments:
    - warn
    - always
    - ignoreConsecutiveComments: true
      ignorePattern: "import|noinspection"
  class-methods-use-this: off
  comma-dangle:
    - error
    - never
  dot-notation: off
  func-names: off
  id-length:
    - warn
    - min: 3
      max: 40
      exceptions: [i, j, x, y, db, dx, dy, el, fs, id, ip, qs, sx, sy, to, tx, ty]
  indent:
    - error
    - 4
    - SwitchCase: 1
      VariableDeclarator: 1
  new-cap:
    - error
    - capIsNewExceptions:
      - CryptoJS.AES
      - CryptoJS.EvpKDF
      - CryptoJS.MD5
      - CryptoJS.PBKDF2
      - CryptoJS.Rabbit
      - CryptoJS.RC4
      - CryptoJS.RIPEMD160
      - CryptoJS.SHA1
      - CryptoJS.SHA3
      - CryptoJS.SHA224
      - CryptoJS.SHA256
      - CryptoJS.SHA384
      - CryptoJS.SHA512
      - CryptoJS.TripleDES
      - Match.Maybe
      - Match.ObjectIncluding
      - Match.OneOf
      - Match.Optional
      - Match.Where
  no-await-in-loop: error
  no-console: error
  no-duplicate-imports: off # Use import/no-duplicate instead, as it supports Flow
  no-eq-null: error
  no-implicit-coercion: error
  no-magic-numbers:
    - warn
    - ignore: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 60, 100, 1000, 3600, 86400]
      ignoreArrayIndexes: true
      enforceConst: true
      detectObjects: false
  no-multi-assign: error
  no-restricted-syntax:
      - error
      - ForInStatement
      - LabeledStatement
      - WithStatement
  no-underscore-dangle: off
  no-use-before-define:
      - error
      - functions: false
        classes: true
  no-useless-call: error
  object-curly-spacing: ["off", "never"]
  prefer-promise-reject-errors: error
  prefer-template: off
  quote-props: ["error", "consistent-as-needed"]
  require-await: error

  # Additional
  unicorn/catch-error-name: error
  unicorn/no-abusive-eslint-disable: error
  # unicorn/no-array-instanceof: error
  # unicorn/no-new-buffer: error
  unicorn/throw-new-error: error

  # Babel
  babel/no-invalid-this: error
  babel/object-curly-spacing: ["error", "never"]

  # JSDoc
  require-jsdoc:
    - warn
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  valid-jsdoc:
    - warn
    - prefer: {returns: return}
      requireReturn: false
      preferType:
        String: string
        Number: number
        Boolean: boolean
        bool: boolean
  jsdoc/check-tag-names: warn
  jsdoc/check-types: warn
  jsdoc/newline-after-description: warn
  jsdoc/require-description-complete-sentence: warn

  # Import
  import/default: error
  import/extensions:
    - error
    - never
    - html: always
  import/named: error
  import/newline-after-import: error
  import/no-absolute-path: off
  import/no-named-as-default: error
  import/no-namespace: error
  import/no-extraneous-dependencies: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      # newlines-between: always
  import/prefer-default-export: off

  # Meteor
  meteor/template-names: ["error", "pascal-case"]
  meteor/no-session: off
  meteor/no-zero-timeout: error
  meteor/prefer-session-equals: error

  # Flowtype
  flowtype/boolean-style:
    - error
    - boolean
  flowtype/define-flow-type:
    - error
  flowtype/delimiter-dangle:
    - error
    - never
  flowtype/generic-spacing:
    - error
    - never
  flowtype/no-dupe-keys: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-weak-types:
    - error
    - any: false
      Function: true
      Object: false
  flowtype/object-type-delimiter:
    - error
    - semicolon
  flowtype/require-parameter-type:
    - warn
    - excludeArrowFunctions: expressionsOnly
      excludeParameterMatch: ^_
  flowtype/require-return-type:
    - warn
    - excludeArrowFunctions: expressionsOnly
  flowtype/require-valid-file-annotation:
    - error
    - always
    - annotationStyle: block
  flowtype/require-variable-type:
    - warn
  flowtype/semi:
    - error
    - always
  flowtype/space-after-type-colon:
    - error
    - always
  flowtype/space-before-generic-bracket:
    - error
    - never
  flowtype/space-before-type-colon:
    - error
    - never
  flowtype/union-intersection-spacing:
    - error
    - always
  flowtype/valid-syntax: error

  # Eslint comments
  eslint-comments/disable-enable-pair: off
  eslint-comments/no-duplicate-disable: error
  eslint-comments/no-unlimited-disable: error
  eslint-comments/no-unused-disable: error
  eslint-comments/no-unused-enable: error
  eslint-comments/no-use:
    - error
    - allow:
      - global
      - eslint-disable
      - eslint-disable-line
      - eslint-disable-next-line
      - eslint-enable
```

**What did you do? Please include the actual source code causing the issue.**

```js
import type {
    HomePageLayoutBlock
} from '/imports/common/types';

...

for (const block: HomePageLayoutBlock of layout.blocks) {
  ...
}
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
> mobile@1.0.0 eslint /Users/dikmax/workspace/project/mobile/app
> eslint --quiet .


/Users/dikmax/workspace/project/mobile/app/imports/client/ui/pages/home/home.js
  15:5  error  'HomePageLayoutBlock' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

Error points to import line.
