### ISSUE TITLE
no-use-before-define false positive

### ISSUE THREAD

**Issue by Alexsey** [eslint/eslint#9335]
**Tell us about your environment**

* **ESLint Version: 4.7.1**
* **Node Version: 8.5.0**
* **npm Version: 5.4.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```yaml
---
parserOptions:
  ecmaVersion: 8
env:
  node: true
rules:
  no-use-before-define:
    - error
    - functions: false
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
const x = ''

function f (a = x) {
  const x = ''
}
```

**What did you expect to happen?**

No error should occurred because first `x` is from the outer scope and second `x` is from the inner scope

**What actually happened? Please include the actual, raw output from ESLint.**
```
ESLint: 'x' was used before it was defined. (no-use-before-define)
```
![screen shot 2017-09-20 at 19 37 54](https://user-images.githubusercontent.com/6392013/30655994-45b8f4a4-9e3b-11e7-9765-7878c0730871.png)
