### ISSUE TITLE
Escape characters are handled incorrectly in inline config comments

### ISSUE THREAD

**Issue by isiahmeadows** [eslint/eslint#9366]
**Tell us about your environment**

* **ESLint Version:** v4.7.2
* **Node Version:** v8.5.0
* **npm Version:** Yarn v1.0.2

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
    id-match: [2, "^(([^$\\W]|\\$[a-f\\d]{2})+|[$_]\\w*|[^\\W\\d]\\w*|[A-Z]([A-Z_]*[A-Z])?)$", {
        properties: true
    }]
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint id-match: [2, "^(([^$\\W]|\\$[a-f\\d]{2})+|[$_]\\w*|[^\\W\\d]\\w*|[A-Z]([A-Z_]*[A-Z])?)$", {properties: true}] */

function is$2dvoid(value) {
    return value == null
}
```

**What did you expect to happen?** It to pass (as it does without the comment)

**What actually happened? Please include the actual, raw output from ESLint.**

```
/path/to/file.js
  3:10  error  Identifier 'is$2dvoid' does not match the pattern '^(([^$\\W]|\\$[a-f\\d]{2})+|[$_]\\w*|[^\\W\\d]\\w*|[A-Z]([A-Z_]*[A-Z])?)$'  id-match

✖ 1 problem (1 error, 0 warnings)
```
