### ISSUE TITLE
spaced-comment implicitly adds space to marker

### ISSUE THREAD

**Issue by Alexsey** [eslint/eslint#9883]
**Tell us about your environment**

* **ESLint Version:** 4.16.0
* **Node Version:** 9.3.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** 

<details>
<summary>Configuration</summary>

```yaml
---
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: script
env:
  node: true
rules:
  spaced-comment:
    - error
    - always
    - markers:
      - global
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/*globalABC*/
```
**What did you expect to happen?**
No error should be reported

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint: Expected space or tab after /*global in comment. (spaced-comment)

I have take this example with `global` from documentation. If you add space after `global` than no error would be risen

So it looks like `marker` is appended with space and there is no way to configure it

Why is it useful? Because sometimes to comment about next section of code something like
`/*********** Next Section **************/`
could be used. And there is no way configure the rule to allow it while having second parameter as `always`
